name: Build Kha_Task App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3

    - name: Installer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt pyinstaller

    - name: Construire l'exécutable avec icône et images
      run: |
        ICON_PATH=""
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          ICON_PATH="icon.ico"
        elif [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
          ICON_PATH="icon.png"
        fi
        pyinstaller --noconfirm --onefile --windowed --icon=$ICON_PATH --add-data "background1.png:." Kha_Task.py

        
    - name: Lister le contenu du dossier dist
      run: |
        ls -l dist/

    - name: Upload de l’exécutable
      uses: actions/upload-artifact@v2
      with:
        name: build-${{ matrix.os }}
        path: dist/*
